### SIGNUP
POST https://localhost/api/users/signup
Content-Type: application/json

{
    "email":"asdf@asdf.com",
    "password":"asdf"
}




### SIGNIN
POST https://localhost/api/users/signin
Content-Type: application/json

{
    "email":"asdf@asdf.com",
    "password":"asdf"
}


### CURRENT USER
GET https://localhost/api/users/currentuser


### SIGN OUT
POST https://localhost/api/users/signout
