### SIGNUP
POST https://localhost/api/users/signup
Content-Type: application/json

{
    "email":"test@asdf.com",
    "password":"asdf"
}




### SIGNIN
POST https://localhost/api/users/signin
Content-Type: application/json

{
    "email":"",
    "password":""
}